import type { Metadata } from "next";
import {Instrument_Sans,Instrument_Serif} from "next/font/google";
import "./globals.css";

const instrumentSans = Instrument_Sans({
  variable: '--font-instrumentSans',
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  weight:['400'],
  subsets: ["latin"],
  style: ["normal", "italic"]
});


export const metadata: Metadata = {
  title: "Design Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${instrumentSans.variable} ${instrumentSerif.style} antialiased flex flex-col items-center h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
